include("gibsplat2/sv_hooks.lua")
include("gibsplat2/constraintinfo.lua")
include("gibsplat2/gibs.lua")
include("gibsplat2/buildcustomragdoll.lua")
include("gibsplat2/buildmesh.lua")

resource.AddWorkshop("2336666211")

AddCSLuaFile("gibsplat2/constraintinfo.lua")
AddCSLuaFile("gibsplat2/buildmesh.lua")
AddCSLuaFile("gibsplat2/gibs.lua")
AddCSLuaFile("gibsplat2/clipmesh.lua")
AddCSLuaFile("gibsplat2/filesystem.lua")
AddCSLuaFile("gibsplat2/mesh_util.lua")
AddCSLuaFile("gibsplat2/decal_util.lua")
AddCSLuaFile("autorun/client/gs2_menu.lua")